### ISSUE TITLE
Unintended redirection?

### ISSUE THREAD

**Issue by oscarlvp** [kevoree/kevoree.github.io#1]
The website redirects to this page:

![image](https://user-images.githubusercontent.com/630717/75884084-7a2fad80-5e24-11ea-9976-f30b650adb48.png)

**Comment by maxleiko** [comment]
Not at all.  

It does not redirect to anything actually.

`kevoree.org` is no longer owned by us anyways ;)

**Comment by oscarlvp** [comment]
When I visit http://kevoree.github.io it redirects to kevoree.org and then to a random page.
Is it only me then?
